*1.3.1 Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.*

In [16]:
import numpy as np

A = [[(x+y) % 2 for x in range(8+1)] for y in range (8+1)]

A

[[0, 1, 0, 1, 0, 1, 0, 1, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 1, 0, 1, 0, 1, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 1, 0, 1, 0, 1, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 1, 0, 1, 0, 1, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 1, 0, 1, 0, 1, 0]]

*1.3.2 Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.*

In [31]:

A = [np.arange(0, 4 + 1) for x in range(0, 5)]

A

[array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4])]

*1.3.3 Создать массив 3x3x3 со случайными значениями*

In [38]:
array_3d = np.random.randint(low = 0, high = 100, size = (3, 3, 3))

print(array_3d)

[[[81 91 30]
  [ 6 42 78]
  [78 98 40]]

 [[63 67 62]
  [53 94 60]
  [45  4 32]]

 [[76 35 40]
  [11 71 28]
  [93 90 50]]]


*1.3.4 Создать матрицу с 0 внутри, и 1 на границах.*

In [41]:
rows, cols = map(int, input().split())

# Создаем матрицу из нулей
matrix = np.zeros((rows, cols), dtype=int)

matrix[0, :] = 1  
matrix[-1, :] = 1 
matrix[:, 0] = 1  
matrix[:, -1] = 1  

print(matrix)

5 5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


*1.3.5 Создайте массив и отсортируйте его по убыванию.*

In [52]:
A = [x for x in range(100)]
A.sort(reverse = True)
print(A)

[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


*1.3.6 Создайте матрицу, выведите ее форму, размер и размерность.*

In [53]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Форма матрицы
shape = matrix.shape
print("Форма матрицы:", shape)

# Количество элементов
size = matrix.size
print("Размер матрицы:", size)

# Размерность матрицы
dimension = matrix.ndim
print("Размерность матрицы:", dimension)

Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


*2.3.1 Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.*

In [56]:
import pandas as pd

a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

sq_diff = (a - b) ** 2
sum_sq_diff = np.sum(sq_diff)
euclidean_distance = np.sqrt(sum_sq_diff)

print("Евклидово расстояние между точками a и b:", euclidean_distance)

Евклидово расстояние между точками a и b: 5.196152422706632


*2.3.2 Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).*


In [58]:
data = pd.read_csv("C:\\Users\\Admin\\Desktop\\diamonds.csv")

data

carat        cut color clarity  depth  table     x     y     z  price
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

[53940 rows x 10 columns]

*2.3.3 Анализ характеристик фрейма данных.*

In [59]:
data.head()

carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

In [60]:
data.tail()

carat        cut color clarity  depth  table     x     y     z  price
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

In [62]:
data.shape

(53940, 10)

In [63]:
data.describe()

carat         depth         table             x             y  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184      5.731157      5.734526   
std        0.474011      1.432621      2.234491      1.121761      1.142135   
min        0.200000     43.000000     43.000000      0.000000      0.000000   
25%        0.400000     61.000000     56.000000      4.710000      4.720000   
50%        0.700000     61.800000     57.000000      5.700000      5.710000   
75%        1.040000     62.500000     59.000000      6.540000      6.540000   
max        5.010000     79.000000     95.000000     10.740000     58.900000   

                  z         price  
count  53940.000000  53940.000000  
mean       3.538734   3932.799722  
std        0.705699   3989.439738  
min        0.000000    326.000000  
25%        2.910000    950.000000  
50%        3.530000   2401.000000  
75%        4.040000   5324.250000  
max       31.800000  18823.000000

*Выберите индивидуальные данные или срезы фрейма данных*

In [65]:
data.iloc[1:4]

carat      cut color clarity  depth  table     x     y     z  price
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334

Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [67]:
premium_yarik = data.loc[data['cut'] == 'Premium']

premium_yarik

carat      cut color clarity  depth  table     x     y     z  price
1       0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
3       0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
12      0.22  Premium     F     SI1   60.4   61.0  3.88  3.84  2.33    342
14      0.20  Premium     E     SI2   60.2   62.0  3.79  3.75  2.27    345
15      0.32  Premium     E      I1   60.9   58.0  4.38  4.42  2.68    345
...      ...      ...   ...     ...    ...    ...   ...   ...   ...    ...
53928   0.79  Premium     E     SI2   61.4   58.0  6.03  5.96  3.68   2756
53930   0.71  Premium     E     SI1   60.5   55.0  5.79  5.74  3.49   2756
53931   0.71  Premium     F     SI1   59.8   62.0  5.74  5.73  3.43   2756
53934   0.72  Premium     D     SI1   62.7   59.0  5.69  5.73  3.58   2757
53938   0.86  Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757

[13791 rows x 10 columns]

*3.3.2 Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.*

In [4]:
data_iris = pd.read_csv("C:\\Users\\Admin\\Desktop\\iris.csv")

data_iris

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [5]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

scaler_MinMax = MinMaxScaler()
scaler_Z = StandardScaler()

data_iris[['sepal_length_cm']] = scaler_MinMax.fit_transform(data_iris[['sepal_length_cm']])
data_iris[['sepal_width_cm']] = scaler_Z.fit_transform(data_iris[['sepal_width_cm']])

In [6]:
data_iris

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]